source "https://api.berkshelf.com"

cookbook 'apt', github: 'opscode-cookbooks/apt'
cookbook 'chef-solo-search', github: 'edelight/chef-solo-search'
cookbook 'build-essential', github: 'opscode-cookbooks/build-essential'
cookbook 'fail2ban', github: 'opscode-cookbooks/fail2ban'
cookbook 'hostnames', github: 'nathantsoi/chef-cookbook-hostname'
cookbook 'locales', github: 'phbergsmann/chef-locales'
cookbook 'look_and_feel-tlq', github: 'TalkingQuickly/look_and_feel-tlq'
cookbook 'monit-tlq', github: 'TalkingQuickly/monit-tlq', branch: 'master'
cookbook 'monit_configs-tlq', github: 'TalkingQuickly/monit_configs-tlq', branch: 'master'
cookbook 'nginx', github: 'miketheman/nginx'
cookbook 'ntp', github: 'gmiranda23/ntp'
cookbook 'openssh', github: 'opscode-cookbooks/openssh'
cookbook 'postgresql', github: 'opscode-cookbooks/postgresql'
cookbook 'rails_gem_dependencies-tlq', github: 'TalkingQuickly/rails_gem_dependencies-tlq'
cookbook 'rbenv', github: 'fnichol/chef-rbenv'
cookbook 'sudo', github: 'opscode-cookbooks/sudo'
cookbook 'ufw', github: 'opscode-cookbooks/ufw'
cookbook 'users', github: 'opscode-cookbooks/users'
cookbook 'nodejs', github: 'redguide/nodejs'
